---
title: "P8105 Homework 5 - Tanya Butt (thb2114)"
output: github_document
---

```{r, echo = FALSE, message = FALSE}
library(tidyverse)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

```{r}
homicide_df = 
  read_csv("homicide-data.csv", na = c("","Unknown")) %>% 
  mutate(
    city_state = str_c(city, state),
    resolution = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
    )) %>% 
    relocate(city_state) %>% 
  filter(city_state != "TulsaAL")
```

Let's focus on Baltimore, MD.

```{r, collapse=TRUE}
baltimore_df =
  homicide_df %>% 
  filter(city_state == "BaltimoreMD")

baltimore_summary =
  baltimore_df %>% 
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )

baltimore_test = 
  prop.test(
    x = baltimore_summary %>%  pull(unsolved), 
    n = baltimore_summary %>%  pull(n))

baltimore_test %>% 
  broom::tidy()
```

Let's try to iterate across cities!

First off, write a function.
```{r, collapse=TRUE}
prop_test_function = function(city_df) {
 
   city_summary =
     city_df %>% 
  summarize(
    unsolved = sum(resolution == "unsolved"),
    n = n()
  )

  city_test = 
    prop.test(
      x = city_summary %>%  pull(unsolved), 
      n = city_summary %>%  pull(n))

return(city_test)

}

prop_test_function(baltimore_df)

homicide_df %>% 
  filter(city_state == "AlbuquerqueNM") %>% 
  prop_test_function()
```

Now, let's iterate across all cities.

```{r, collapse=TRUE}
results_df = 
  homicide_df %>% 
  nest(data = uid:resolution) %>% 
  mutate(
    test_results = map(data, prop_test_function),
    tidy_results = map(test_results, broom::tidy)
  ) %>% 
  select(city_state, tidy_results) %>% 
  unnest(tidy_results) %>% 
  select(city_state, estimate, starts_with("conf"))

```

Try to make a plot showing estimates and confidence intervals.

```{r, collapse = TRUE}
results_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate )) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

## Problem 2

```{r, collapse=TRUE}
problem2_df = 
  tibble(
    files = list.files("./data/")
   )

read_data <- function(file_name) {
  read_csv(paste0("./data/", file_name))
}

study_data =
  problem2_df %>%
  mutate(
    individual_data = map(files, read_data)) %>% 
  unnest(individual_data) %>%
  separate(
    files, c("experiment_arm", "ID"), "_") %>% 
  mutate(
    ID = gsub(".csv","",ID)) %>% 
  mutate(
    ID = as.character(ID)
  ) %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "weeks",
    values_to = "observation") 

study_data %>% 
group_by(experiment_arm) %>% 
ggplot( 
  aes(x = weeks, y = observation, color = ID)) +
  geom_line(aes(group = ID)) +
  theme(legend.text = element_text(size = 8), legend.spacing.x = unit(0.05, 'cm'), 
        legend.position = 'right') +
   xlab("Weeks") + ylab("Observation") +
   scale_colour_discrete(name = "ID")
```


